/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file is auto-generated by TanStack Router's Vite plugin.
// Do not manually edit this file — it will be overwritten on the next build.

// Import Routes
import { Route as rootRoute } from "./routes/__root";
import { Route as IndexImport } from "./routes/index";
import { Route as BookingImport } from "./routes/booking";

// Create Virtual Routes

// Create/Update Routes

const IndexRoute = IndexImport.update({
  id: "/",
  path: "/",
  getParentRoute: () => rootRoute,
} as never);

const BookingRoute = BookingImport.update({
  id: "/booking",
  path: "/booking",
  getParentRoute: () => rootRoute,
} as never);

// Populate the FileRoutesByPath interface

declare module "@tanstack/react-router" {
  interface FileRoutesByPath {
    "/": {
      id: "/";
      path: "/";
      fullPath: "/";
      preLoaderRoute: typeof IndexImport;
      parentRoute: typeof rootRoute;
    };
    "/booking": {
      id: "/booking";
      path: "/booking";
      fullPath: "/booking";
      preLoaderRoute: typeof BookingImport;
      parentRoute: typeof rootRoute;
    };
  }
}

// Create and export the route tree

export interface FileRoutesByFullPath {
  "/": typeof IndexRoute;
  "/booking": typeof BookingRoute;
}

export interface FileRoutesByTo {
  "/": typeof IndexRoute;
  "/booking": typeof BookingRoute;
}

export interface FileRoutesById {
  __root__: typeof rootRoute;
  "/": typeof IndexRoute;
  "/booking": typeof BookingRoute;
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath;
  fullPaths: "/" | "/booking";
  fileRoutesByTo: FileRoutesByTo;
  to: "/" | "/booking";
  id: "__root__" | "/" | "/booking";
  fileRoutesById: FileRoutesById;
}

export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute;
  BookingRoute: typeof BookingRoute;
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  BookingRoute: BookingRoute,
};

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>();
